
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARROBA CONSONANTES DATE DIGSEG EMISOR ENTIDAD NAMECURP NUMAS NUMBANCO NUMCUENTA ORGANIZACION PALABRA PROTOCOLO PUNTO SEXO SLASH TLDcomando : entradaentrada : PROTOCOLO SLASH SLASH dominioweb TLD SLASHdominioweb : PALABRA PUNTO PALABRAentrada : PALABRA ARROBA dominiodominio : ORGANIZACION TLDentrada : NAMECURP DATE SEXO ENTIDAD CONSONANTES NUMASentrada : EMISOR NUMBANCO NUMCUENTA DIGSEG'
    
_lr_action_items = {'PROTOCOLO':([0,],[3,]),'PALABRA':([0,11,22,],[4,17,25,]),'NAMECURP':([0,],[5,]),'EMISOR':([0,],[6,]),'$end':([1,2,12,18,20,24,26,],[0,-1,-4,-5,-7,-2,-6,]),'SLASH':([3,7,21,],[7,11,24,]),'ARROBA':([4,],[8,]),'DATE':([5,],[9,]),'NUMBANCO':([6,],[10,]),'ORGANIZACION':([8,],[13,]),'SEXO':([9,],[14,]),'NUMCUENTA':([10,],[15,]),'TLD':([13,16,25,],[18,21,-3,]),'ENTIDAD':([14,],[19,]),'DIGSEG':([15,],[20,]),'PUNTO':([17,],[22,]),'CONSONANTES':([19,],[23,]),'NUMAS':([23,],[26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comando':([0,],[1,]),'entrada':([0,],[2,]),'dominio':([8,],[12,]),'dominioweb':([11,],[16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comando","S'",1,None,None,None),
  ('comando -> entrada','comando',1,'p_start','sintactico.py',72),
  ('entrada -> PROTOCOLO SLASH SLASH dominioweb TLD SLASH','entrada',6,'p_url','sintactico.py',76),
  ('dominioweb -> PALABRA PUNTO PALABRA','dominioweb',3,'p_dominio_web','sintactico.py',82),
  ('entrada -> PALABRA ARROBA dominio','entrada',3,'p_correo','sintactico.py',88),
  ('dominio -> ORGANIZACION TLD','dominio',2,'p_dominio_correo','sintactico.py',94),
  ('entrada -> NAMECURP DATE SEXO ENTIDAD CONSONANTES NUMAS','entrada',6,'p_curp','sintactico.py',98),
  ('entrada -> EMISOR NUMBANCO NUMCUENTA DIGSEG','entrada',4,'p_tarjeta','sintactico.py',104),
]
