
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARROBA CONSONANTES DATE DIGSEG EMISOR ENTIDAD NAMECURP NUMAS NUMBANCO NUMCUENTA ORGANIZACION PALABRA PROTOCOLO PUNTO SEXO SLASH TLDcomando : entradadominioweb : PALABRA PUNTO PALABRAentrada : PALABRA ARROBA dominiodominio : ORGANIZACION TLDentrada : NAMECURP DATE SEXO ENTIDAD CONSONANTES NUMASentrada : EMISOR NUMBANCO NUMCUENTA DIGSEG'
    
_lr_action_items = {'PALABRA':([0,],[3,]),'NAMECURP':([0,],[4,]),'EMISOR':([0,],[5,]),'$end':([1,2,9,13,15,17,],[0,-1,-3,-4,-6,-5,]),'ARROBA':([3,],[6,]),'DATE':([4,],[7,]),'NUMBANCO':([5,],[8,]),'ORGANIZACION':([6,],[10,]),'SEXO':([7,],[11,]),'NUMCUENTA':([8,],[12,]),'TLD':([10,],[13,]),'ENTIDAD':([11,],[14,]),'DIGSEG':([12,],[15,]),'CONSONANTES':([14,],[16,]),'NUMAS':([16,],[17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comando':([0,],[1,]),'entrada':([0,],[2,]),'dominio':([6,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comando","S'",1,None,None,None),
  ('comando -> entrada','comando',1,'p_start','sintactico.py',58),
  ('dominioweb -> PALABRA PUNTO PALABRA','dominioweb',3,'p_dominio_web','sintactico.py',66),
  ('entrada -> PALABRA ARROBA dominio','entrada',3,'p_correo','sintactico.py',71),
  ('dominio -> ORGANIZACION TLD','dominio',2,'p_dominio_correo','sintactico.py',76),
  ('entrada -> NAMECURP DATE SEXO ENTIDAD CONSONANTES NUMAS','entrada',6,'p_curp','sintactico.py',79),
  ('entrada -> EMISOR NUMBANCO NUMCUENTA DIGSEG','entrada',4,'p_tarjeta','sintactico.py',84),
]
